#!/usr/bin/env python3
import sys, pathlib
env      = sys.argv[1] if len(sys.argv) > 1 else "LINUX_NO_KVM"
is_arm   = env.startswith("APPLE_M")
is_kvm   = (env == "LINUX_KVM")
platform = "linux/arm64" if is_arm else "linux/amd64"
accel    = "kvm" if is_kvm else "tcg"
lines = []
lines.append("version: \"3.8\"")
lines.append("services:")
lines.append("  postgres:")
lines.append("    image: postgres:15")
lines.append("    platform: linux/amd64")
lines.append("    environment:")
lines.append("      POSTGRES_DB: noriben")
lines.append("      POSTGRES_USER: noriben")
lines.append("      POSTGRES_PASSWORD: noriben123")
lines.append("    ports:")
lines.append("      - \"5432:5432\"")
lines.append("    volumes:")
lines.append("      - noriben_pg:/var/lib/postgresql/data")
lines.append("    healthcheck:")
lines.append("      test: [\"CMD\",\"pg_isready\",\"-U\",\"noriben\"]")
lines.append("      interval: \"5s\"")
lines.append("      retries: 5")
lines.append("  redis:")
lines.append("    image: redis:7-alpine")
lines.append("    ports:")
lines.append("      - \"6379:6379\"")
lines.append("  api:")
lines.append("    build:")
lines.append("      context: .")
lines.append("      dockerfile: Dockerfile")
lines.append("      platform: " + platform)
lines.append("    ports:")
lines.append("      - \"8000:8000\"")
lines.append("    volumes:")
lines.append("      - .:/app")
lines.append("      - ./vms:/shared")
lines.append("    environment:")
lines.append("      DATABASE_URL: postgresql://noriben:noriben123@postgres/noriben")
lines.append("      CELERY_BROKER: redis://redis:6379/0")
lines.append("      NORIBEN_ENV: " + env)
lines.append("    depends_on:")
lines.append("      postgres:")
lines.append("        condition: service_healthy")
lines.append("      redis:")
lines.append("        condition: service_started")
lines.append("  celery:")
lines.append("    build:")
lines.append("      context: .")
lines.append("      dockerfile: Dockerfile")
lines.append("      platform: " + platform)
lines.append("    command: celery -A noriben_soc.tasks worker --loglevel=info --concurrency=4")
lines.append("    volumes:")
lines.append("      - .:/app")
lines.append("      - ./vms:/shared")
lines.append("    environment:")
lines.append("      DATABASE_URL: postgresql://noriben:noriben123@postgres/noriben")
lines.append("      CELERY_BROKER: redis://redis:6379/0")
lines.append("      QEMU_ACCEL: " + accel)
lines.append("      NORIBEN_ENV: " + env)
lines.append("    depends_on:")
lines.append("      - redis")
lines.append("      - postgres")
lines.append("  grafana:")
lines.append("    image: grafana/grafana:latest")
lines.append("    ports:")
lines.append("      - \"3000:3000\"")
lines.append("    environment:")
lines.append("      GF_SECURITY_ADMIN_PASSWORD: admin")
lines.append("    volumes:")
lines.append("      - noriben_grafana:/var/lib/grafana")
lines.append("      - ./grafana/provisioning:/etc/grafana/provisioning")
lines.append("volumes:")
lines.append("  noriben_pg: {}")
lines.append("  noriben_grafana: {}")
out = pathlib.Path(__file__).parent.parent / "docker-compose.yml"
out.write_text("\n".join(lines) + "\n")
print(f"[gen_compose] OK ({env} | {platform} | {accel})")
